# TODO: https://docs.travis-ci.com/user/multi-cpu-architectures/

language: go
go: 1.16.x
  
git:
    quiet: true

os: linux
dist: bionic

stages:
  - Test
  - name: Deploy
    if: tag IS present

jobs:
  fast_finish: true
  include:
    - stage: "Deploy"
      name: "Deploy to GitHub Releases"
      script: ./.travisci/deploy.sh
      deploy:
        provider: releases
        token: $GITHUB_TOKEN
        file:
          - "./src/LevelDBDumper/LevelDBDumper"
          - "./src/LevelDBDumper/LevelDBDumper.app.zip"
          - "./src/LevelDBDumper/LevelDBDumper.exe"
          - "./src/LevelDBDumper/LevelDBDumper_x86.exe"
          - "./src/LevelDBDumper/LevelDBDumper_x86"
        draft: true
        skip_cleanup: true
        name: "LevelDB Dumper $TRAVIS_TAG"
        on:
          tags: true

before_install:
  - chmod +x ./.travisci/before_install.sh
  - ./.travisci/before_install.sh